---
name: Run Check

on:
  pull_request:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  JAVA_VERSION: 17
  RUBY_VERSION: 3.2.2

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
          # Allow subsequent steps to trigger GitHub Actions via git push
          # https://github.community/t/push-from-action-even-with-pat-does-not-trigger-action/17622
          persist-credentials: false

      - name: Configure Ruby
        uses: ruby/setup-ruby@af848b40be8bb463a751551a1180d74782ba8a72 # v1.162.0
        with:
          bundler-cache: true
          ruby-version: ${{ env.RUBY_VERSION }}

      - name: Configure JDK
        uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93 # v4.0.0
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Build and Run Check
        # Run checks while excluding release-build tests, which are not configured to work properly
        # with the Compose testing library.
        run: ./gradlew check -x testStandardRelease -x testFdroidRelease koverXmlReportStandardDebug

      - name: Danger
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bundle exec danger
